
name: node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      use: actions/checkout@v3

    - name: setup node
      use: actions/node-setup@v3
      with:
        node-version: 18.19.1
        cache: npm
      
    - name: run dependencies
      run: npm ci
    
    - name: run test
      run: npm test
    
    - name: Generate coverage report
      run: npm run test -- --coverage

    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

   - name: Create GitHub Issue on failure
    if: failure()
    uses: actions/github-script@v6
    with:
      script: |
        const { data: issue } = await github.rest.issues.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: `CI Pipeline Failed: ${context.job}`,
          body: `🚨 CI pipeline failed for ${context.repo.owner}/${context.repo.repo}. Please check the details [here](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
        });
        console.log(`Created issue: ${issue.html_url}`);
