name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Generate coverage report
      run: npm run test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # setup SAST with CodeQl
    - name: setup CodeQl
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    
    - name: perform code analysis
      uses: github/codeql-action/analyze@v3

      # Dependency scanning
    - name: Run npm audit
      run: npm audit --audit-level=high
    
    # Secret detection using TruffleHog
    - name: Secret scanning
      uses: trufflesecurity/trufflehog@v3
      with:
        scan: 'true'


    - name: Create GitHub Issue on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const { data: issue } = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `CI Pipeline Failed: ${context.job}`,
            body: `🚨 CI pipeline failed for ${context.repo.owner}/${context.repo.repo}. Please check the details [here](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
          });
          console.log(`Created issue: ${issue.html_url}`);
