
name: node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1'
        cache: npm
      
    - name: run dependencies
      run: npm ci
    
    - name: run test
      run: npm test
    
